# certs.yml
tls:
  certificates:
    - certFile: /etc/traefik/certs/erp.hbr.test.pem
      keyFile: /etc/traefik/certs/erp.hbr.test-key.pem
    - certFile: /etc/traefik/certs/erp.langmaster.test.pem
      KeyFile: /etc/traefik/certs/erp.langmaster.test-key.pem
    - certFile: /etc/traefik/certs/yusic.test.pem
      KeyFile: /etc/traefik/certs/yusic.test-key.pem
    - certFile: /etc/traefik/certs/fcm.langtech.test.pem
      KeyFile: /etc/traefik/certs/fcm.langtech.test-key.pem
    - certFile: /etc/traefik/certs/template.hbr.test.pem
      KeyFile: /etc/traefik/certs/template.hbr.test-key.pem
    - certFile: /etc/traefik/certs/hbr.edu.test.pem
      KeyFile: /etc/traefik/certs/hbr.edu.test-key.pem
